ColmanNews/Models/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace eCommerce.Models
{
    public class Article
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false), Required]
        [DisplayName("Post Date")]
        public DateTime CreationDate { get; set; }

        public string AuthorUserName { get; set; }

        public User Author { get; set; }

        [DisplayName("Genre")]
        public int GenreId { get; set; }

        public virtual Genre Genre { get; set; }

        public ICollection<Comment> Comments { get; set; } = new List<Comment>();

        [DisplayName("Image")]
        [ForeignKey("Image")]
        public int? ImageId { get; set; }

        public virtual Image Image { get; set; }
    }
}

ColmanNews/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ColmanNews.Data;
using eCommerce.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.IO;

namespace ColmanNews.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly ColmanNewsContext _context;

        public ArticlesController(ColmanNewsContext context)
        {
            _context = context;
        }

        // GET: Articles
        public async Task<IActionResult> Index()
        {
            return View(await GetReporterArticles());
        }

        // GET: Articles
        public async Task<IActionResult> Home()
        {
            ViewBag.Users = await _context.Users.ToListAsync();
            ViewBag.Genres = await _context.Genres.ToListAsync();
            return View(await GetArticles());
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .Include(article => article.Author)
                .Include(article => article.Genre)
                .Include(article => article.Image)
                .Include(article => article.Comments)
                    .ThenInclude(comment => comment.Commenter)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            await UpdateUserGenreCount(article);
            ViewBag.SuggestedArticles = await GetSuggestedArticles(article);
            return View(article);
        }

        // GET: Articles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,GenreId,AuthorUserName")] Article article)
        {
            article.Author = await _context.Users.FindAsync(this.User.Claims.FirstOrDefault(c => c.Type == "Username")?.Value);
            article.CreationDate = DateTime.Now;

            var genre = await _context.Genres.FindAsync(article.GenreId);
            article.Genre = genre;

            if (article.Author != null)
            {
                Image img = new Image();
                if (Request.Form.Files.Count() > 0)
                {
                    var file = Request.Form.Files[0];
                    img.ImageTitle = file.FileName;

                    MemoryStream ms = new MemoryStream();
                    file.CopyTo(ms);
                    img.ImageData = ms.ToArray();

                    ms.Close();
                    ms.Dispose();

                    _context.Add(img);
                    _context.SaveChanges();

                    article.ImageId = img.Id;
                }
                _context.Add(article);
                await _context.SaveChangesAsync();

                var numberOfArticlesPostedTodayInSameGenre = _context.Articles
                    .Where(a => a.GenreId == article.GenreId).AsEnumerable()
                    .Where(a => IsSameDate(a.CreationDate, DateTime.Now)).Count();

                // Post to Facebook if it's the first post of the day in it's genre
                if (numberOfArticlesPostedTodayInSameGenre == 1)
                {
                    using (var client = new HttpClient())
                    {
                        const string KEY = "EAAFyqHgDOFQBAIJeBX8U2FksPHCF3i53QYnccXmunApGZBZANbZB9uceoViHdSPb6mBFxU79Bm28lZCMbiAdXOAv07OKPRQjv3DkZCgg1xTrHDCIjBo3fFHVLOccr4p4UL7liLIEh0TomT5tq0nkhbHNG9kUqCGHviqnjJLMfoCEsTWDrVzbYkHlZAN7IVtGIZD";
                        string post = "📰👓 Check out our new article in " + article.Genre.Name + "! ➡ " + article.Title;

                        HttpRequestMessage requestMessage = new HttpRequestMessage(
                            HttpMethod.Post,
                            "https://graph.facebook.com/110024000913635/feed?message=" + post + "&access_token=" + KEY
                            );

                        HttpResponseMessage response = client.SendAsync(requestMessage).GetAwaiter().GetResult();
                    }
                };

                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        private bool IsSameDate(DateTime firstDate, DateTime secondDate)
        {
            return firstDate.Date == secondDate.Date
                && firstDate.Month == secondDate.Month
                && firstDate.Year == secondDate.Year;
        }

        // GET: Articles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var article = await _context.Articles.Include(article => article.Genre).Where(article => article.Id == id).FirstOrDefaultAsync();
            if (article == null)
            {
                return NotFound();
            }
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,GenreId,AuthorUserName")] Article article)
        {
            if (id != article.Id)
            {
                return NotFound();
            }
            article.Author = await _context.Users.FindAsync(this.User.Claims.FirstOrDefault(c => c.Type == "Username")?.Value);

            if (article.Author != null)
            {
                Image img = new Image();
                if (Request.Form.Files.Count() > 0)
                {
                    var file = Request.Form.Files[0];
                    img.ImageTitle = file.FileName;

                    MemoryStream ms = new MemoryStream();
                    file.CopyTo(ms);
                    img.ImageData = ms.ToArray();

                    ms.Close();
                    ms.Dispose();

                    _context.Add(img);
                    _context.SaveChanges();

                    article.ImageId = img.Id;
                } else
                {
                    Article savedInDbArticle = await _context.Articles
                            .Include(article => article.Author)
                            .Include(article => article.Genre)
                            .Include(article => article.Image)
                            .Include(article => article.Comments)
                            .ThenInclude(comment => comment.Commenter)
                            .FirstOrDefaultAsync(m => m.Id == id);
                    article.ImageId = savedInDbArticle.ImageId;
                    article.Image = savedInDbArticle.Image;

                    _context.Entry(savedInDbArticle).State = EntityState.Detached;
                }

                var genre = await _context.Genres.FindAsync(article.GenreId);
                article.Genre = genre;
                try
                {
                    _context.Update(article);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed([FromBody] Article article)
        {
            var articleToDelete = await _context.Articles.FindAsync(article.Id);
            if (articleToDelete != null)
            {
                _context.Articles.Remove(articleToDelete);
                await _context.SaveChangesAsync();
                return Json(new { success = true, responseText = JsonConvert.SerializeObject(articleToDelete) });
            }

            _context.Articles.Remove(articleToDelete);
            await _context.SaveChangesAsync();
            return Json(new { success = false, responseText = JsonConvert.SerializeObject(articleToDelete) });
        }

        private bool ArticleExists(int id)
        {
            return _context.Articles.Any(e => e.Id == id);
        }

        private async Task<ICollection<Article>> GetReporterArticles()
        {
            var username = this.User.Claims.FirstOrDefault(c => c.Type == "Username")?.Value;
            var myArticles = await _context.Articles
                .Include(article => article.Genre)
                .Include(article => article.Comments)
                .Include(article => article.Image)
                .Include(article => article.Author)
                .Where(article => article.AuthorUserName == username)
                .OrderByDescending(article => article.CreationDate)
                .ToListAsync();
            return myArticles;
        }

        private async Task<ICollection<Article>> GetArticles()

ColmanNews/Views/Articles/Details.cshtml
@model eCommerce.Models.Article
@using System.Globalization;

@{
    ViewData["Title"] = "Details";
    var comments = Model.Comments.OrderByDescending(comment => comment.CreationDate);
    List<eCommerce.Models.Article> suggestedArticles = ViewBag.SuggestedArticles;
}

<style>
    .article-title {
        font-family: "Lucida Console", Monaco, monospace;
        margin-bottom: 5px;
        margin-bottom: 10px;
        margin-top: 25px;
    }

    .article-meta {
        color: #9fbfe7;
        font-family: "Lucida Console", Monaco, monospace;
    }

    .article-all-meta {
        border-bottom: solid;
        padding-bottom: 20px;
        border-bottom-width: 1px;
        border-color: #9fbfe7;
        margin-bottom: 25px;
    }

    .article-content {
        white-space: pre-wrap;
        font-family: "Lucida Console", Monaco, monospace;
        font-size: 18px;

        @*Multi Column*@
        column-count: 2;
        column-gap: 40px;
        column-rule-style: solid;
        column-rule-width: 1px;
    }

    .comment-content {
        font-size: 17px;
    }

    .comment-footer {
        font-size: 10px;
    }

    .editCommentSection {
        font-size: 10px;
    }

    .comment-blockquote {
        border-left: solid;
        padding-left: 10px;
        border-color: #8080806b;
    }
</style>


<center>
    <div class="row">
        <div class="col-md-9">
            @if (Model.Image == null)
            {
                <img width="100%" height="450px" src="~/images/genres/@(Model.Genre.Name + ".png")" />
            }
            else
            {
                <img width="100%" height="450px" src="data:image/png;base64, @Convert.ToBase64String(Model.Image.ImageData, Base64FormattingOptions.InsertLineBreaks)" alt="Red dot" />
            }
            <h1 class="article-title">@Html.DisplayFor(model => model.Title)</h1>

            <div class="row article-all-meta">
                <div class="col">
                    <h6 class="article-meta">By: @Html.DisplayFor(model => model.Author.FirstName) @Html.DisplayFor(model => model.Author.LastName)</h6>
                </div>

                <div class="col">
                    <h6 class="article-meta">@Html.DisplayFor(model => model.Genre.Name)</h6>
                </div>

                <div class="col">
                    <h6 class="article-meta">@Html.DisplayFor(model => model.CreationDate)</h6>
                </div>
            </div>

            <div class="p-2 bd-highlight text-wrapper article-content">@Model.Content</div>
        </div>

        <div style="padding-left: 3px" class="col">
            
            <h2 style="font-family: DifiqueMenre;"> Suggested Articles </h2>
            @foreach (var article in suggestedArticles)
            {
                <div style="margin:auto" class="article-details-box row align-items-center my-4">
                    <div style="margin:auto">
                        @if (article.ImageId != null)
                        {
                            <img width="70" class="article-image img-thumbnail" src="data:image/png;base64, @Convert.ToBase64String(article.Image.ImageData, Base64FormattingOptions.InsertLineBreaks)" />
                        }
                        else
                        {
                            <img width="70" class="article-image img-thumbnail" alt="@article.Genre.Name image" src="~/images/genres/@(article.Genre.Name + ".png")" />
                        }
                    </div>
                    <div class="article-details col">
                        <a asp-controller="Articles" asp-action="Details" asp-route-id="@article.Id" style="text-decoration: none;"><h3>@article.Title</h3></a>
                        <div class="article-small-details row mx-auto">
                            <i class="fa fa-globe" aria-hidden="true"></i>
                            <div class="mx-2">@article.Author.FirstName @article.Author.LastName</div>
                            <div class="mx-2">@article.Genre.Name</div>
                            <div class="mx-2">@article.CreationDate.ToString("m", CultureInfo.CreateSpecificCulture("en-US"))</div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</center>




<br />
<br />
<br />
<div>
    <button id="addCommentLink"
            href="#"
            data-toggle="modal"
            data-target="#postCommentModal"
            type="button"
            class="btn btn-light">
        Comment
    </button>

    @if (this.User.Claims.ToList()[0].Value == Model.Author.Username)
    {
        <span id="editArticle">
            |
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
        </span>
    }

</div>
<br />
<br />
<br />
@foreach (var item in comments)
{
    <blockquote class="blockquote comment-blockquote">
        <p class="mb-0 comment-content">@item.Content</p>
        <footer class="blockquote-footer comment-footer">@item.Commenter.FirstName @item.Commenter.LastName, <cite>@item.CreationDate</cite></footer>

        @if (this.User.Claims.ToList()[0].Value == item.Commenter.Username)
        {

            <aside class="editCommentSection" data-commenterId="@item.CommenterUserName">
                <a class="editCommentLink"
                   href="#"
                   data-id="@item.Id"
                   data-content="@item.Content"
                   data-toggle="modal"
                   data-target="#editCommentModal"
                   onclick="setEditSelectedComment(this)">
                    Edit
                </a> |
                <a class="deleteCommentLink"
                   href="#"
                   data-id="@item.Id"
                   data-toggle="modal"
                   data-target="#deleteCommentModal"
                   onclick="setDeleteSelectedComment(this)">
                    Delete
                </a>
            </aside>
        }
    </blockquote>

    <br />
}

<!-- Post New Comment Modal -->
<div class="modal fade" id="postCommentModal" tabindex="-1" role="dialog" aria-labelledby="postCommentLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="postCommentLabel">Leave a comment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <textarea id="postCommentContent" class="commentContent" rows="3"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button id="btnPostComment" type="button" class="btn btn-primary">Post</button>
            </div>
        </div>
    </div>
</div>

<!-- Edit Comment Modal -->
<div class="modal fade" id="editCommentModal" tabindex="-1" role="dialog" aria-labelledby="editCommentLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editCommentLabel">Edit comment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <textarea id="editCommentContent" class="commentContent" rows="3"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button id="btnEditComment" type="button" class="btn btn-primary">Edit</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete Comment Modal -->
<div class="modal fade" id="deleteCommentModal" tabindex="-1" role="dialog" aria-labelledby="deleteCommentLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteCommentLabel">Delete comment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this comment?
            </div>
            <div class="modal-footer">
                <button id="btnCancelEditComment" type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button id="btnDeleteComment" type="button" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        // --- Functions ---
        const getMyUsername = () => "@Context.User.Claims.FirstOrDefault(c => c.Type == "Username")?.Value";

        let commentIdToEdit = null;
        let commentIdToDelete = null;

        const postComment = (content) => {
            const username = getMyUsername();
            const comment = {
                content: content,
                CommenterUserName: username,
                articleId: @Model.Id
            };
            $.ajax({
                url: "/Comments/Create",
                type: "post",
                dataType: "json",
                contentType: "application/json",
                success: () => {
                    $('#postCommentModal').modal('hide');
                    location.reload(true);
                },
                data: JSON.stringify(comment)
            });
        }

        const setOnPostComment = () => {
            $("#btnPostComment").click(() => {
                postComment($("#postCommentContent").val());
            });
        };

        const editComment = (id, content) => {
            const comment = {
                id: id,
                content: content
            };
            $.ajax({
                url: "/Comments/Edit",
                type: "post",
                dataType: "json",
                contentType: "application/json",
                success: () => {
                    $('#editCommentModal').modal('hide');
                    location.reload(true);
                },
                data: JSON.stringify(comment)
            });
        }

        const setEditSelectedComment = (commentElement) => {
            commentIdToEdit = parseInt(commentElement.dataset.id);
            $("#editCommentContent").val(commentElement.dataset.content)
        };

        const setOnEditComment = () => {
            $("#btnEditComment").click(() => {
                editComment(commentIdToEdit, $("#editCommentContent").val());
            });
        }

        const setUpdateCommentVisibility = () => {
            const myUsername = getMyUsername();
            const isAdmin = @Context.User.IsInRole("Admin").ToString().ToLower();
            const comments = $(".editCommentSection");
            $.each(comments, (index, comment) => {
                const commenterId = comment.getAttribute("data-commenterId");
                if (!isAdmin && commenterId != myUsername) {
                    comment.setAttribute("hidden", "true")
                }
            });
        }

        const setDeleteSelectedComment = (commentElement) => {
            commentIdToDelete = parseInt(commentElement.dataset.id);
        }

        const deleteComment = (commentId) => {
            const id = {
                id: commentId
            }

            $.ajax({
                url: "/Comments/Delete",
                type: "post",
                contentType: "application/json",
                contentType: "application/json",
                success: () => {
                    $('#deleteCommentModal').modal('hide');
                    location.reload(true);
                },
                data: JSON.stringify(id)
            });
        }

        const setOnDeleteComment = () => {
            $("#btnDeleteComment").click(() => {
                deleteComment(commentIdToDelete);
            });
        }

        const setEditArticleVisibility = () => {
            const myUsername = getMyUsername();
            const isAdmin = @Context.User.IsInRole("Admin").ToString().ToLower();
            const authorUsername = "@Model.AuthorUserName";
            if (!isAdmin && authorUsername != myUsername) {
                $("#editArticle").hide();
            }
        }

        // --- END Functions ---

        setOnPostComment();
        setOnEditComment();
        setOnDeleteComment();
        setEditArticleVisibility();

    </script>
}

ColmanNews/Views/Articles/Home.cshtml
@model IEnumerable<eCommerce.Models.Article>
@using System.Globalization;

@{
    ViewData["Title"] = "Home Page";
}

<style>
    .smurf-phrase {
        font-size: 30px;
        text-align: center;
        font-family: DifiqueMenre;
        color: #0096dd;
    }

    .lower-navbar-genres {
        display: flex;
        justify-content: center;
    }
</style>


<nav class="lower-navbar">
    <div class="lower-navbar-genres">
        @{
            foreach (eCommerce.Models.Genre genre in ViewBag.Genres)
            {
                <a class="p-2" asp-controller="Genres" asp-action="Details" asp-route-id="@genre.Id">@genre.Name</a>
            }
        }
     </div>
</nav>

<div class="row">
    <div class="col">
        <video style="background-color: black !important;" width="100%" height="400px" loop autoplay>
            <source src="../images/smurf.mp4" type="video/mp4">
            Your browser does not support HTML video.
        </video>
        <p class="smurf-phrase">Smurf our site! 📘</p>
    </div>
    <!-- Leaflet scripts -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>

    <!-- This is where the map will be -->
    <div class="col">
        <div id="mapDiv" style="width: 60vh; height: 60vh"></div>
        <h1 style="font-family: DifiqueMenre;">Our Smurf Reporters</h1>
    </div>
</div>


<div>
    <div class="recent-article-boxes">
        <h1 style="font-family: DifiqueMenre;">Recent Smurticles</h1>
        @{

            foreach (var article in Model.ToList().Take(7))
            {
                <div class="article-details-box row align-items-center my-4">
                    <div>
                        @if (article.ImageId != null)
                        {
                            <img width="70" class="article-image img-thumbnail" src=@ViewBag.articleImageUrls[article.Id] />
                        }
                        else
                        {
                            <img width="70" class="article-image img-thumbnail" alt="@article.Genre.Name image" src="~/images/genres/@(article.Genre.Name + ".png")" />
                        }
                    </div>
                    <div class="article-details col">
                        <a asp-controller="Articles" asp-action="Details" asp-route-id="@article.Id" style="text-decoration: none;"><h3>@article.Title</h3></a>
                        <div class="article-small-details row mx-auto">
                            <i class="fa fa-globe" aria-hidden="true"></i>
                            <div class="mx-2">@article.Author.FirstName @article.Author.LastName</div>
                            <div class="mx-2">@article.Genre.Name</div>
                            <div class="mx-2">@article.CreationDate.ToString("m", CultureInfo.CreateSpecificCulture("en-US"))</div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

@section scripts {
    <section class="scripts">
        <script>

            // initialize map
            map = L.map('mapDiv');

            // set map tiles source
            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
                maxZoom: 18,
            }).addTo(map);

            // Get the maps data from the controller, in JSON format
            var reporters = @Html.Raw(Json.Serialize(ViewBag.Users));

            // Using the JQuery "each" selector to iterate through the Maps list from the controller and drop marker pins
            $.each(reporters, function (i, reporter) {

                $.ajax('https://nominatim.openstreetmap.org/search?format=json&q=' + reporter.address)
                    .done(function (addressDetails) {
                        // position we will use later
                        var lat = addressDetails[0].lat;
                        var lon = addressDetails[0].lon;
                        // add marker to the map
                        marker = L.marker([lat, lon]).addTo(map);
                        // add popup to the marker
                        marker.bindPopup("<b>" + reporter.firstName + " " + reporter.lastName + "</b><br />" + reporter.address);
                    })
            })
            $.ajax('https://nominatim.openstreetmap.org/search?format=json&q=israel')
                .done(function (addressDetails) {
                    map.setView([addressDetails[0].lat, addressDetails[0].lon], 7);
                })

        </script>
    </section>
}

ColmanNews/Views/Articles/SearchResults.cshtml
@model IEnumerable<eCommerce.Models.Article>
@using System.Globalization;

@{
    ViewData["Title"] = "Search Results";
}

<h1>
    Search Results
</h1>

<h4>
    @if (Model.Count() == 0)
    {
        <span>No</span>
    }
    Smurticles found for "@ViewBag.SearchTerm" by
    @if (ViewBag.ReporterName == null)
    {
        <span>all authors</span>
    }
    else
    {
        <span>@ViewBag.ReporterName</span>
    }
    in
    @if (ViewBag.Genre == null)
    {
        <span>all genres</span>
    }
    else
    {
        <span>@ViewBag.Genre</span>
    }
</h4>

<table class="table">
    <tbody>
        @foreach (var article in Model)
        {
            <div class="article-details-box row align-items-center my-4">
                <div>
                    @if (article.ImageId != null)
                    {
                        <img width="70" class="article-image img-thumbnail" src=@ViewBag.articleImageUrls[article.Id] />
                    }
                    else
                    {
                        <img width="70" class="article-image img-thumbnail" alt="@article.Genre.Name image" src="~/images/genres/@(article.Genre.Name + ".png")" />
                    }
                </div>
                <div class="article-details col">
                    <a asp-controller="Articles" asp-action="Details" asp-route-id="@article.Id" style="text-decoration: none;"><h3>@article.Title</h3></a>
                    <div class="article-small-details row mx-auto">
                        <i class="fa fa-globe" aria-hidden="true"></i>
                        <div class="mx-2">@article.Author.FirstName @article.Author.LastName</div>
                        <div class="mx-2">@article.Genre.Name</div>
                        <div class="mx-2">@article.CreationDate.ToString("m", CultureInfo.CreateSpecificCulture("en-US"))</div>
                    </div>
                </div>
            </div>
        }


    </tbody>
</table>